const express = require('express');
const app = express();

app.use(express.static('public'));
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

function spinArticle(text) {
    const wordMap = {
        "happy": ["joyful", "cheerful", "delighted", "content"],
        "sad": ["unhappy", "miserable", "gloomy", "depressed"],
        "gourmet": ["epicurean", "foodie", "connoisseur", "gastronome"],
        "savory": ["flavorful", "tasty", "appetizing", "palatable"],
        "delectable": ["delicious", "scrumptious", "mouthwatering", "tempting"],
        "pastry": ["baked goods", "baked delicacies", "confections", "sweet treats"],
        "beverage": ["drink", "liquid refreshment", "potable", "libation"],
        "cuisine": ["cooking", "culinary art", "food preparation", "cookery"],
        "culinary": ["cooking", "gastronomic", "culinary arts", "cookery"],
        "epicurean": ["gourmet", "food lover", "connoisseur", "luxury eater"],
        "anthropology": ["human studies", "cultural studies", "human science", "social science"],
        "psychology": ["mind science", "mental health science", "behavioral science", "psyche study"],
        "sociology": ["social science", "society study", "social studies", "community analysis"],
        "ethnography": ["cultural analysis", "cultural study", "ethnology", "fieldwork"],
        "criminology": ["crime science", "criminal behavior study", "forensic science", "lawbreaking analysis"],
        "demography": ["population study", "population analysis", "vital statistics", "population science"],
        "political science": ["government studies", "political analysis", "politics science", "policy study"],
        "economics": ["economic science", "financial studies", "economic analysis", "financial science"],
        "linguistics": ["language science", "language study", "linguistic analysis", "speech analysis"],
        "geography": ["land study", "earth science", "topography", "terrain analysis"],
        "monetary": ["financial", "economic", "cash-related", "fiscal"],
        "inflation": ["price increase", "rising prices", "escalation", "cost surge"],
        "deflation": ["price decrease", "falling prices", "decline", "reduction"],
        "recession": ["downturn", "slump", "economic decline", "depression"],
        "stimulus": ["boost", "incentive", "encouragement", "impetus"],
        "market": ["trading place", "commerce", "exchange", "financial market"],
        "stock": ["share", "equity", "securities", "investment"],
        "capitalism": ["free market economy", "free enterprise", "private enterprise", "laissez-faire"],
        "investment": ["asset", "venture", "financial commitment", "investment"],
        "bankruptcy": ["insolvency", "financial ruin", "destitution", "financial collapse"],
        "justice": ["fairness", "equity", "righteousness", "impartiality"],
        "legislation": ["laws", "statutes", "regulations", "enactment"],
        "litigation": ["lawsuit", "legal action", "dispute", "legal proceedings"],
        "jurisdiction": ["authority", "power", "control", "legal right"],
        "acquittal": ["exoneration", "absolution", "clearing", "vindication"],
        "conviction": ["guilt", "sentence", "condemnation", "verdict"],
        "testimony": ["evidence", "witness statement", "declaration", "affidavit"],
        "constitutional": ["legal", "lawful", "statutory", "authorized"],
        "appeal": ["petition", "request", "plea", "call"],
        "prosecution": ["charge", "accusation", "indictment", "legal action"],
        "calculation": ["computation", "estimation", "reckoning", "math"],
        "theorem": ["proof", "axiom", "proposition", "postulate"],
        "integral": ["whole", "complete", "entire", "total"],
        "derivative": ["secondary", "derived", "resultant", "subsequent"],
        "algebra": ["mathematics", "equations", "variables", "formulas"],
        "geometry": ["shape analysis", "spatial mathematics", "figures study", "measurement"],
        "probability": ["likelihood", "chance", "odds", "likelihood"],
        "numeric": ["numerical", "quantitative", "number-based", "mathematical"],
        "analysis": ["examination", "investigation", "study", "scrutiny"],
        "fraction": ["portion", "segment", "division", "share"],
        "topography": ["terrain", "landscape", "relief", "lay of the land"],
        "plateau": ["highland", "tableland", "upland", "plain"],
        "canyon": ["gorge", "ravine", "valley", "gully"],
        "archipelago": ["group of islands", "island chain", "island cluster", "island group"],
        "isthmus": ["narrow passage", "neck", "narrow strip of land", "land bridge"],
        "basin": ["valley", "depression", "hollow", "cavity"],
        "delta": ["estuary", "river mouth", "alluvial fan", "marshland"],
        "tectonic": ["geological", "seismic", "plate-related", "earthquake-related"],
        "erosion": ["wear and tear", "deterioration", "degradation", "corrosion"],
        "continental": ["land-based", "mainland", "landmass", "terra firma"],
        "vaccine": ["inoculation", "immunization", "shot", "jab"],
        "pandemic": ["global outbreak", "epidemic", "crisis", "spread"],
        "immunity": ["resistance", "protection", "defenses", "immunization"],
        "therapy": ["treatment", "counseling", "healing", "rehabilitation"],
        "diagnosis": ["identification", "analysis", "assessment", "detection"],
        "symptom": ["indication", "sign", "manifestation", "warning"],
        "prescription": ["medication", "drug", "remedy", "formula"],
        "pharmacy": ["drugstore", "chemist's", "apothecary", "dispensary"],
        "biomedical": ["medical science", "life science", "bioengineering", "biotechnology"],
        "genomics": ["genetics", "genetic mapping", "genome analysis", "genetic study"],
        "celestial": ["heavenly", "stellar", "astral", "cosmic"],
        "cosmos": ["universe", "space", "galaxy", "heavens"],
        "astronomy": ["astrophysics", "cosmology", "celestial science", "stargazing"],
        "constellation": ["star pattern", "asterism", "star grouping", "stellar configuration"],
        "nebula": ["galactic cloud", "stellar cloud", "cosmic dust", "interstellar cloud"],
        "supernova": ["stellar explosion", "exploding star", "nova", "stellar blast"],
        "black hole": ["singularity", "gravitational collapse", "cosmic vacuum", "event horizon"],
        "satellite": ["orbiter", "spacecraft", "space probe", "artificial moon"],
        "astronaut": ["cosmonaut", "spacefarer", "space explorer", "space traveler"],
        "orbit": ["trajectory", "path", "course", "rotation"],
        "melody": ["tune", "harmony", "music", "song"],
        "rhythm": ["beat", "tempo", "cadence", "pulse"],
        "harmony": ["accord", "concord", "agreement", "balance"],
        "composition": ["creation", "opus", "piece", "work"],
        "orchestration": ["arrangement", "organization", "coordination", "deployment"],
        "symphony": ["concerto", "sonata", "opera", "musical work"],
        "improvisation": ["spontaneity", "creativity", "ingenuity", "resourcefulness"],
        "choreography": ["dance arrangement", "movement composition", "dance design", "routine arrangement"],
        "acoustics": ["sound properties", "auditory effects", "sonic characteristics", "sound science"],
        "jazz": ["blues", "swing", "ragtime", "improvisational music"],
        "prose": ["writing", "composition", "narrative", "text"],
        "fiction": ["novel", "story", "tale", "narrative"],
        "verse": ["poetry", "lyrics", "rhyme", "stanza"],
        "literature": ["writing", "prose", "fiction", "poetry"],
        "narrative": ["storytelling", "account", "chronicle", "tale"],
        "poetry": ["verse", "rhyme", "lyrics", "sonnet"],
        "novel": ["book", "story", "tale", "fiction"],
        "essay": ["composition", "article", "paper", "discussion"],
        "drama": ["play", "theater", "theatricals", "performance"],
        "literary": ["artistic", "creative", "imaginative", "cultural"],
        "metaphysics": ["ontology", "cosmology", "transcendental philosophy", "speculative philosophy"],
        "ethics": ["moral philosophy", "moral principles", "moral values", "ethical theory"],
        "morality": ["ethicality", "rightness", "virtue", "goodness"],
        "existentialism": ["individualism", "freedom", "subjectivity", "authenticity"],
        "philosophy": ["wisdom", "reasoning", "logic", "rationality"],
        "epistemology": ["theory of knowledge", "knowledge theory", "gnoseology", "cognition theory"],
        "ontology": ["study of being", "philosophy of existence", "metaphysics", "existence theory"],
        "ethics": ["moral philosophy", "moral principles", "moral values", "ethical theory"],
        "deontology": ["duty-based ethics", "obligation ethics", "duty-bound ethics", "moral obligation theory"],
        "utilitarianism": ["consequentialism", "greatest happiness principle", "utility theory", "utilitarian ethics"],
        "innovation": ["invention", "discovery", "advancement", "breakthrough"],
        "research": ["study", "investigation", "analysis", "examination"],
        "experiment": ["trial", "test", "procedure", "investigation"],
        "discovery": ["finding", "uncovering", "realization", "revelation"],
        "technology": ["engineering", "electronics", "digitalization", "informatics"],
        "automation": ["mechanization", "robotics", "computerization", "digitization"],
        "algorithm": ["procedure", "method", "formula", "protocol"],
        "data": ["information", "facts", "statistics", "figures"],
        "cybersecurity": ["information security", "digital security", "computer security", "IT security"],
        "biotechnology": ["genetic engineering", "bioengineering", "life science", "bioinformatics"],
        "breathtaking": ["awe-inspiring", "stunning", "spectacular", "mesmerizing"],
        "tranquil": ["serene", "calm", "peaceful", "placid"],
        "majestic": ["grand", "impressive", "stately", "noble"],
        "scenic": ["picturesque", "beautiful", "panoramic", "charming"],
        "pristine": ["unspoiled", "pure", "untouched", "virgin"],
        "verdant": ["lush", "green", "luxuriant", "lush-green"],
        "cosmic": ["celestial", "universal", "interstellar", "stellar"],
        "ethereal": ["celestial", "heavenly", "otherworldly", "transcendent"],
        "luminous": ["radiant", "glowing", "bright", "shining"],
        "elemental": ["fundamental", "basic", "primary", "essential"],
        "entrepreneur": ["businessperson", "innovator", "tycoon", "mogul"],
        "venture": ["undertaking", "enterprise", "project", "initiative"],
        "startup": ["beginning", "launch", "initiation", "commencement"],
        "innovation": ["invention", "creativity", "novelty", "breakthrough"],
        "investment": ["capital", "funding", "financing", "backing"],
        "strategy": ["plan", "approach", "tactics", "method"],
        "partnership": ["alliance", "collaboration", "association", "union"],
        "negotiation": ["discussion", "bargaining", "compromise", "deal-making"],
        "enterprise": ["business", "venture", "undertaking", "company"],
        "success": ["achievement", "accomplishment", "triumph", "victory"],
        "heritage": ["legacy", "tradition", "inheritance", "ancestry"],
        "antiquity": ["ancientness", "olden days", "archaism", "age-old"],
        "legacy": ["inheritance", "heritage", "bequest", "endowment"],
        "archaeology": ["study of antiquity", "excavation", "prehistoric study", "anthropology"],
        "historical": ["historic", "past", "epochal", "epoch-making"],
        "cultural": ["ethnic", "traditional", "ethnical", "societal"],
        "ancestral": ["hereditary", "inherited", "forefather's", "familial"],
        "artifact": ["relic", "remnant", "historical object", "archeological find"],
        "civilization": ["culture", "society", "community", "world"],
        "tradition": ["custom", "ritual", "practice", "convention"],
        "democracy": ["representative government", "self-government", "majority rule", "rule by the people"],
        "legislation": ["laws", "statutes", "regulations", "rules"],
        "governance": ["administration", "management", "stewardship", "direction"],
        "diplomacy": ["negotiation", "tact", "foreign affairs", "international relations"],
        "citizenship": ["membership", "belonging", "nationality", "identity"],
        "lobbying": ["advocacy", "campaigning", "influencing", "persuasion"],
        "policy": ["plan", "strategy", "approach", "course of action"],
        "constituency": ["electorate", "voters", "population", "citizens"],
        "bureaucracy": ["administration", "officialdom", "government", "authorities"],
        "referendum": ["vote", "plebiscite", "poll", "ballot"],
        "eloquent": ["articulate", "expressive", "fluent", "persuasive"],
        "articulate": ["well-spoken", "clear", "expressive", "eloquent"],
        "concise": ["brief", "succinct", "terse", "to the point"],
        "articulation": ["expression", "enunciation", "pronunciation", "speech"],
        "persuasive": ["convincing", "compelling", "influential", "effective"],
        "debate": ["discussion", "argument", "disputation", "controversy"],
        "dialogue": ["conversation", "discussion", "exchange", "talk"],
        "communicative": ["expressive", "open", "talkative", "interactive"],
        "fluency": ["proficiency", "ease", "facility", "mastery"],
        "eloquence": ["articulateness", "expressiveness", "fluency", "rhetoric"],
        "tranquility": ["serenity", "calmness", "peacefulness", "quietness"],
        "serenity": ["peacefulness", "calmness", "placidity", "composure"],
        "euphoria": ["exhilaration", "elation", "ecstasy", "bliss"],
        "contentment": ["satisfaction", "happiness", "fulfillment", "gratification"],
        "agitation": ["restlessness", "nervousness", "anxiety", "unease"],
        "melancholy": ["sadness", "gloom", "despondency", "dejection"],
        "apathy": ["indifference", "unconcern", "passivity", "disinterest"],
        "jubilation": ["celebration", "rejoicing", "elation", "joy"],
        "nostalgia": ["longing", "sentimentality", "yearning", "wistfulness"],
        "restlessness": ["uneasiness", "agitation", "disquiet", "discontent"],
        "athletic": ["sporty", "active", "fit", "sporting"],
        "endurance": ["stamina", "perseverance", "resilience", "persistence"],
        "agility": ["nimbleness", "quickness", "dexterity", "adroitness"],
        "strength": ["power", "might", "force", "potency"],
        "flexibility": ["adaptability", "pliability", "suppleness", "versatility"],
        "conditioning": ["fitness", "training", "preparation", "physical condition"],
        "teamwork": ["collaboration", "cooperation", "unity", "partnership"],
        "competitiveness": ["rivalry", "ambition", "drive", "determination"],
        "sportsmanship": ["fairness", "integrity", "ethics", "honour"],
        "performance": ["execution", "presentation", "delivery", "achievement"],
        "integrity": ["honesty", "uprightness", "rectitude", "probity"],
        "compassion": ["empathy", "kindness", "sympathy", "humanity"],
        "altruism": ["selflessness", "benevolence", "philanthropy", "generosity"],
        "justice": ["fairness", "equality", "impartiality", "righteousness"],
        "morality": ["ethics", "principles", "virtue", "decency"],
        "honor": ["integrity", "dignity", "respectability", "nobility"],
        "empathy": ["understanding", "compassion", "sensitivity", "concern"],
        "righteousness": ["virtue", "goodness", "uprightness", "integrity"],
        "principled": ["ethical", "moral", "righteous", "upright"],
        "virtue": ["goodness", "morality", "righteousness", "excellence"],
        "visionary": ["imaginative", "creative", "innovative", "forward-thinking"],
        "strategic": ["calculated", "deliberate", "methodical", "planned"],
        "charismatic": ["inspiring", "magnetic", "captivating", "influential"],
        "inspirational": ["motivational", "uplifting", "encouraging", "empowering"],
        "delegator": ["assigner", "distributor", "allocator", "apportioner"],
        "diplomatic": ["tactful", "politic", "sensitive", "thoughtful"],
        "assertive": ["confident", "self-assured", "decisive", "firm"],
        "mentor": ["guide", "counselor", "advisor", "tutor"],
        "facilitator": ["enabler", "organizer", "catalyst", "coordinator"],
        "influential": ["persuasive", "compelling", "convincing", "impactful"],
        "affectionate": ["loving", "caring", "warm", "tender"],
        "devoted": ["committed", "loyal", "dedicated", "faithful"],
        "endearing": ["adorable", "lovable", "charming", "sweet"],
        "cherished": ["treasured", "valued", "prized", "esteemed"],
        "admired": ["respected", "esteemed", "applauded", "appreciated"],
        "empathetic": ["understanding", "compassionate", "caring", "sensitive"],
        "sympathetic": ["caring", "concerned", "supportive", "empathetic"],
        "tenderhearted": ["compassionate", "kind-hearted", "gentle", "tender"],
        "adoring": ["loving", "fond", "affectionate", "adoring"],
        "receptive": ["open-minded", "accepting", "welcoming", "responsive"],
        "resilient": ["robust", "tough", "strong", "durable"],
        "adaptive": ["flexible", "versatile", "adjustable", "malleable"],
        "vitality": ["energy", "vigor", "liveliness", "vital force"],
        "balance": ["equilibrium", "harmony", "stability", "moderation"],
        "rejuvenation": ["revitalization", "renewal", "refreshment", "reinvigoration"],
        "wellness": ["health", "fitness", "well-being", "soundness"],
        "mindfulness": ["awareness", "consciousness", "presence", "attention"],
        "nourishment": ["nutrition", "sustenance", "nutriment", "food"],
        "holistic": ["comprehensive", "complete", "overall", "integrative"],
        "restorative": ["healing", "renewing", "rehabilitative", "restful"],
        "adventurous": ["daring", "bold", "courageous", "exploratory"],
        "wanderlust": ["itch for travel", "desire to explore", "craving for adventure", "love of travel"],
        "itinerary": ["travel plan", "schedule", "route", "program"],
        "voyage": ["journey", "trip", "expedition", "adventure"],
        "sojourn": ["visit", "stay", "stopover", "respite"],
        "destination": ["location", "place", "end-point", "goal"],
        "globetrotter": ["world traveler", "wanderer", "nomad", "explorer"],
        "exotic": ["unusual", "foreign", "unfamiliar", "strange"],
        "sightseeing": ["touring", "exploring", "visiting attractions", "seeing the sights"],
        "expedition": ["journey", "campaign", "mission", "adventure"],
        "delicious": ["tasty", "scrumptious", "mouthwatering", "flavorful"],
        "gourmet": ["fine dining", "culinary", "epicurean", "haute cuisine"],
        "savory": ["flavorful", "appetizing", "tasty", "palatable"],
        "decadent": ["indulgent", "luxurious", "rich", "opulent"],
        "nutritious": ["healthy", "nourishing", "wholesome", "nutrient-rich"],
        "exquisite": ["delicate", "refined", "elegant", "rare"],
        "spicy": ["hot", "flavorful", "piquant", "zesty"],
        "crispy": ["crunchy", "brittle", "crackling", "textured"],
        "refreshing": ["invigorating", "revitalizing", "rejuvenating", "bracing"],
        "delectable": ["scrumptious", "appetizing", "tempting", "irresistible"],
        "expressive": ["emotive", "artistic", "evocative", "communicative"],
        "abstract": ["non-representational", "non-objective", "conceptual", "symbolic"],
        "impressionistic": ["suggestive", "evocative", "expressive", "artistic"],
        "masterpiece": ["classic", "magnum opus", "gem", "work of art"],
        "sculpture": ["statue", "carving", "figure", "effigy"],
        "photography": ["visual art", "pictures", "images", "photographic art"],
        "sketch": ["drawing", "doodle", "outline", "rough draft"],
        "portrait": ["depiction", "likeness", "image", "representation"],
        "collage": ["montage", "mélange", "collection", "assembly"],
        "mural": ["wall painting", "fresco", "artwork", "painting"],
        "trendy": ["stylish", "fashionable", "in vogue", "hip"],
        "chic": ["elegant", "stylish", "sophisticated", "fashionable"],
        "vibrant": ["colorful", "lively", "bright", "dynamic"],
        "sophisticated": ["refined", "elegant", "cultivated", "classy"],
        "fashion-forward": ["innovative", "avant-garde", "progressive", "cutting-edge"],
        "couture": ["high fashion", "designer clothing", "tailored fashion", "custom-made"],
        "accessory": ["add-on", "embellishment", "ornament", "decoration"],
        "ensemble": ["outfit", "attire", "clothing", "dress"],
        "haute couture": ["high fashion", "exclusive fashion", "designer clothing", "couture fashion"],
        "statement piece": ["bold fashion item", "attention-grabbing piece", "distinctive item", "standout piece"],
        "knowledgeable": ["informed", "erudite", "learned", "well-read"],
        "intellectual": ["cerebral", "academic", "scholarly", "brainy"],
        "inquisitive": ["curious", "inquiring", "probing", "inquiring"],
        "analytical": ["logical", "methodical", "reasoned", "systematic"],
        "perceptive": ["observant", "discerning", "insightful", "aware"],
        "studious": ["diligent", "conscientious", "devoted", "serious"],
        "resourceful": ["ingenious", "creative", "adaptable", "capable"],
        "astute": ["sharp", "canny", "clever", "discerning"],
        "articulate": ["eloquent", "expressive", "fluent", "persuasive"],
        "scholarly": ["academic", "learned", "erudite", "bookish"],
        "green": ["ecological", "environmentally friendly", "sustainable", "eco-friendly"],
        "pristine": ["unspoiled", "untouched", "pure", "virgin"], 
        "lush": ["luxuriant", "verdant", "abundant", "plush"],
        "serene": ["calm", "tranquil", "peaceful", "placid"],
        "bucolic": ["rustic", "pastoral", "rural", "countryside"],
        "flourishing": ["thriving", "prosperous", "booming", "blooming"],
        "scenic": ["picturesque", "beautiful", "panoramic", "scenic"],
        "vibrant": ["dynamic", "energetic", "lively", "animated"],
        "majestic": ["grand", "impressive", "noble", "stately"],
        "regenerative": ["renewing", "restorative", "rejuvenating", "rehabilitative"],
        "cutting-edge": ["innovative", "state-of-the-art", "advanced", "leading-edge"],
        "automated": ["robotic", "mechanized", "self-operating", "automatic"],
        "digital": ["electronic", "computerized", "virtual", "cyber"],
        "groundbreaking": ["pioneering", "revolutionary", "trailblazing", "epoch-making"],
        "high-tech": ["advanced", "sophisticated", "modern", "technologically advanced"],
        "smart": ["intelligent", "clever", "innovative", "advanced"],
        "interactive": ["participatory", "collaborative", "engaging", "responsive"],
        "wireless": ["cordless", "unwired", "radio", "remote"],
        "digitalized": ["computerized", "virtual", "automated", "electronic"],
        "state-of-the-art": ["cutting-edge", "advanced", "modern", "latest"],
        "prosperous": ["wealthy", "affluent", "well-off", "successful"],
        "thriving": ["booming", "flourishing", "successful", "prosperous"],
        "financially stable": ["secure", "solvent", "well-capitalized", "sound"],
        "profitable": ["lucrative", "gainful", "remunerative", "productive"],
        "entrepreneurial": ["innovative", "enterprising", "business-minded", "creative"],
        "sustainable": ["viable", "lasting", "sensible", "practical"],
        "marketable": ["saleable", "commercial", "in-demand", "popular"],
        "resilient economy": ["strong economy", "robust economy", "stable economy", "healthy economy"],
        "fiscally responsible": ["prudent", "financially prudent", "sensible", "cautious"],
        "financial independence": ["self-reliance", "autonomy", "financial autonomy", "self-sufficiency"],
        "friendly": ["amiable", "affable", "cordial", "sociable"],
        "loyal": ["faithful", "devoted", "dedicated", "committed"],
        "trustworthy": ["reliable", "dependable", "honest", "faithful"],
        "compassionate": ["empathetic", "sympathetic", "tender-hearted", "kind-hearted"],
        "forgiving": ["merciful", "lenient", "pardoning", "understanding"],
        "supportive": ["encouraging", "helpful", "nurturing", "uplifting"],
        "understanding": ["empathetic", "comprehending", "perceptive", "tolerant"],
        "communicative": ["talkative", "expressive", "articulate", "vocal"],
        "respectful": ["courteous", "polite", "considerate", "deferential"],
        "cooperative": ["collaborative", "accommodating", "flexible", "amicable"],
        "healthy": ["fit", "well", "robust", "sound"],
        "energetic": ["vibrant", "dynamic", "lively", "vigorous"],
        "rested": ["refreshed", "rejuvenated", "revived", "recharged"],
        "active": ["dynamic", "engaged", "vital", "energetic"],
        "balanced": ["harmonious", "equitable", "proportionate", "well-adjusted"],
        "calm": ["serene", "tranquil", "placid", "peaceful"],
        "resilient": ["tough", "durable", "strong", "hardy"],
        "mindful": ["aware", "attentive", "conscious", "perceptive"],
        "soothing": ["calming", "relaxing", "pacifying", "tranquilizing"],
        "wholesome": ["healthy", "nutritious", "beneficial", "salubrious"],
        "productive": ["efficient", "effective", "fruitful", "prolific"],
        "innovative": ["creative", "original", "ingenious", "groundbreaking"],
        "dedicated": ["committed", "devoted", "loyal", "zealous"],
        "organized": ["methodical", "systematic", "orderly", "structured"],
        "driven": ["motivated", "ambitious", "determined", "goal-oriented"],
        "professional": ["courteous", "competent", "expert", "qualified"],
        "analytical": ["logical", "critical", "methodical", "reasoned"],
        "collaborative": ["cooperative", "team-oriented", "joint", "united"],
        "efficient": ["effective", "productive", "capable", "competent"],
        "adaptable": ["flexible", "versatile", "adjustable", "open-minded"],
        "melancholic": ["sorrowful", "dejected", "pensive", "despondent"],
        "blissful": ["ecstatic", "joyful", "euphoric", "radiant"],
        "bittersweet": ["poignant", "wistful", "mournful", "sorrowful"],
        "nostalgic": ["sentimental", "longing", "rememorative", "wistful"],
        "agitated": ["disturbed", "restless", "turbulent", "unsettled"],
        "triumphant": ["victorious", "successful", "triumphal", "exultant"],
        "determined": ["resolute", "decisive", "persistent", "unwavering"],
        "awe-inspiring": ["breathtaking", "astonishing", "majestic", "awe-inducing"],
        "rejuvenated": ["refreshed", "revitalized", "recharged", "reinvigorated"],
        "invigorated": ["energized", "revived", "stimulated", "animated"],
        "happy": ["cheerful", "joyful", "elated", "ecstatic"],
        "excited": ["enthusiastic", "thrilled", "eager", "animated"],
        "hopeful": ["optimistic", "confident", "positive", "expectant"],
        "grateful": ["thankful", "appreciative", "obliged", "indebted"],
        "content": ["satisfied", "fulfilled", "pleased", "happy"],
        "proud": ["pleased", "honored", "self-respecting", "satisfied"],
        "passionate": ["enthusiastic", "fervent", "ardent", "zealous"],
        "amazed": ["astonished", "astounded", "bewildered", "surprised"],
        "optimistic": ["positive", "hopeful", "confident", "upbeat"],
        "confident": ["assured", "self-assured", "certain", "secure"],
        "sad": ["unhappy", "sorrowful", "depressed", "gloomy"],
        "angry": ["furious", "irate", "enraged", "incensed"],
        "anxious": ["worried", "nervous", "apprehensive", "uneasy"],
        "afraid": ["scared", "frightened", "terrified", "panicked"],
        "lonely": ["solitary", "isolated", "desolate", "unaccompanied"],
        "disappointed": ["let down", "dismayed", "discouraged", "unfulfilled"],
        "embarrassed": ["ashamed", "humiliated", "mortified", "chagrined"],
        "jealous": ["envious", "covetous", "resentful", "green-eyed"],
        "guilty": ["culpable", "remorseful", "ashamed", "contrite"],
        "frustrated": ["exasperated", "irritated", "vexed", "disheartened"],
        "kind": ["compassionate", "benevolent", "caring", "considerate"],
        "intelligent": ["smart", "clever", "bright", "astute"],
        "creative": ["imaginative", "innovative", "artistic", "original"],
        "generous": ["benevolent", "magnanimous", "liberal", "charitable"],
        "brave": ["courageous", "fearless", "valiant", "heroic"],
        "honest": ["truthful", "sincere", "forthright", "upright"],
        "patient": ["tolerant", "enduring", "unperturbed", "long-suffering"],
        "ambitious": ["driven", "aspiring", "determined", "goal-oriented"],
        "confident": ["assured", "self-assured", "poised", "self-reliant"],
        "humorous": ["funny", "witty", "amusing", "comical"],
        "beautiful": ["gorgeous", "stunning", "lovely", "attractive"],
        "handsome": ["good-looking", "attractive", "charming", "dashing"],
        "elegant": ["refined", "graceful", "sophisticated", "polished"],
        "graceful": ["elegant", "poised", "refined", "dignified"],
        "radiant": ["glowing", "beaming", "shining", "luminous"],
        "charming": ["captivating", "enchanting", "alluring", "appealing"],
        "youthful": ["young", "juvenile", "fresh", "vibrant"],
        "attractive": ["appealing", "enticing", "desirable", "charming"],
        "glamorous": ["elegant", "alluring", "sophisticated", "stylish"],
        "vivacious": ["lively", "bubbly", "effervescent", "animated"],
        "smart": ["intelligent", "bright", "clever", "brilliant"],
        "wise": ["sage", "knowledgeable", "judicious", "prudent"],
        "astute": ["perceptive", "shrewd", "keen", "discerning"],
        "knowledgeable": ["informed", "educated", "learned", "erudite"],
        "intellectual": ["cerebral", "academic", "scholarly", "brainy"],
        "analytical": ["logical", "methodical", "reasoned", "systematic"],
        "intuitive": ["instinctive", "perceptive", "empathetic", "insightful"],
        "savvy": ["knowledgeable", "shrewd", "astute", "experienced"],
        "literate": ["educated", "cultured", "well-read", "literate"],
        "erudite": ["scholarly", "learned", "knowledgeable", "cultivated"],



        "Is": ["stands as", "represents", "constitutes", "functions as"],
"It": ["that entity", "the thing", "that object", "this thing"],
"There": ["over yonder", "at that place", "in that area", "at that spot"],
"Was": ["took form as", "manifested as", "existed as", "appeared as"],
"Were": ["existed as", "manifested as", "were present as", "took form as"],
"Has": ["possessed", "held", "owned", "carried"],
"Have": ["possess", "hold", "own", "carry"],
"Been": ["occurred as", "happened as", "taken place as", "existed as"],
"Could": ["had the potential to", "was in a position to", "was able to"],
"Would": ["was inclined to", "had the tendency to", "had the propensity to"],
"Will": ["is set to", "is destined to", "is slated to", "is about to"],
"May": ["might potentially", "could possibly", "may potentially", "might perhaps"],
"Might": ["could possibly", "may potentially", "might perhaps", "could conceivably"],
"Can": ["has the ability to", "is able to", "is capable of", "has the capacity to"],
"Do": ["execute", "perform", "fulfill", "carry through"],
"Does": ["executes", "performs", "carries out", "accomplishes"],
"Did": ["executed", "performed", "carried out", "accomplished"],
"Am": ["exist as", "serve as", "function as", "embody as"],
"Are": ["exist as", "serve as", "function as", "embody as"],
"A": ["a single", "one particular", "an individual", "a solitary"],
"An": ["a single", "one particular", "an individual", "a solitary"],
"The": ["that particular", "this particular", "those particular", "these particular"],
"In": ["within", "inside of", "amidst", "enclosed within"],
"On": ["resting upon", "atop", "sitting on", "on the surface of"],
"At": ["situated at", "present at", "located at", "positioned at"],
"For": ["intended for", "aimed for", "purposed for", "meant for"],
"To": ["towards", "in the direction of", "leading to", "approaching"],
"From": ["originating from", "stemming from", "emerging from", "coming from"],
"By": ["through", "via", "using", "through the means of"],
"With": ["accompanied by", "alongside", "in the company of", "together with"],
"is": ["stands as", "represents", "constitutes", "functions as"],
"it": ["that entity", "the thing", "that object", "this thing"],
"there": ["over yonder", "at that place", "in that area", "at that spot"],
"was": ["took form as", "manifested as", "existed as", "appeared as"],
"were": ["existed as", "manifested as", "were present as", "took form as"],
"has": ["possessed", "held", "owned", "carried"],
"have": ["possess", "hold", "own", "carry"],
"been": ["occurred as", "happened as", "taken place as", "existed as"],
"could": ["had the potential to", "was in a position to", "was able to"],
"would": ["was inclined to", "had the tendency to", "had the propensity to"],
"will": ["is set to", "is destined to", "is slated to", "is about to"],
"may": ["might potentially", "could possibly", "may potentially", "might perhaps"],
"might": ["could possibly", "may potentially", "might perhaps", "could conceivably"],
"can": ["has the ability to", "is able to", "is capable of", "has the capacity to"],
"do": ["execute", "perform", "fulfill", "carry through"],
"does": ["executes", "performs", "carries out", "accomplishes"],
"did": ["executed", "performed", "carried out", "accomplished"],
"am": ["exist as", "serve as", "function as", "embody as"],
"are": ["exist as", "serve as", "function as", "embody as"],
"a": ["a single", "one particular", "an individual", "a solitary"],
"an": ["a single", "one particular", "an individual", "a solitary"],
"the": ["that particular", "this particular", "those particular", "these particular"],
"in": ["within", "inside of", "amidst", "enclosed within"],
"on": ["resting upon", "atop", "sitting on", "on the surface of"],
"at": ["situated at", "present at", "located at", "positioned at"],
"For": ["intended for", "aimed for", "purposed for", "meant for"],
"To": ["towards", "in the direction of", "leading to", "approaching"],
"From": ["originating from", "stemming from", "emerging from", "coming from"],
"By": ["through", "via", "using", "through the means of"],
"With": ["accompanied by", "alongside", "in the company of", "together with"],
"Is not": ["Isn't", "Isn't going to"],
"Has not": ["Hasn't", "Has no chance of"],
"Does not": ["Doesn't", "Doesn't stand a chance"],
"Did not": ["Didn't", "Didn't happen"],
"Would not": ["Wouldn't", "Wouldn't really occur"],
"Can not": ["Can't", "Can't possibly"],
"Could not": ["Couldn't", "Couldn't ever"],
"Should not": ["Shouldn't", "Shouldn't even think of"],
"is not": ["Isn't", "Isn't going to"],
"has not": ["Hasn't", "Has no chance of"],
"does not": ["Doesn't", "Doesn't stand a chance"],
"did not": ["Didn't", "Didn't happen"],
"would not": ["Wouldn't", "Wouldn't really occur"],
"can not": ["Can't", "Can't possibly"],
"could not": ["Couldn't", "Couldn't ever"],
"should not": ["Shouldn't", "Shouldn't even think of"],

        // Add more words and their synonyms
    };

    const spunText = text.split(' ').map(word => {
        if (word.toLowerCase() in wordMap) {
            const synonyms = wordMap[word.toLowerCase()];
            const randomSynonym = synonyms[Math.floor(Math.random() * synonyms.length)];
            return randomSynonym;
        } else {
            return word;
        }
    }).join(' ');

    return spunText;
}

app.post('/spin', (req, res) => {
    const originalText = req.body.text;
    const spunText = spinArticle(originalText);
    res.send(spunText);
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
